[package]
name = "editor-types-parser"
version = "0.0.6"
homepage = "https://github.com/ulyssa/modalkit/tree/main/crates/editor-types-parser"
readme = "README.md"
description = "A library for parsing the editor-types action syntax"
exclude = [".github", "CONTRIBUTING.md"]
keywords = []
categories = ["text-editors"]

edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pomelo = "0.2.3"
logos = "0.16"
thiserror = { workspace = true }
unescape_zero_copy = "2.4"

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }
